name: "PV Manager"
description: "Smart energy manager for home photovoltaic systems"
version: "0.2.1"
slug: "pv-manager"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
boot: auto
ingress: true
ingress_port: 8099
panel_icon: mdi:home-battery
panel_title: PV Manager
hassio_api: true
homeassistant_api: true
host_network: false
ports:
  8099/tcp: null
ports_description:
  8099/tcp: Web interface (not needed when using ingress)
options: {}
schema: {}

